export enum ProjectContentEnum {
    GALAGA_TITLE = 'Galaga Game',
    OPENMP_TITLE = 'Image filtering',
    DISTRIBUTED_SYS_TITLE = 'Messaging service',
    OPERATIVE_SYSTEM_DESIGN_TITLE = 'IoT weather station',
    CRACKING_PASS_TITLE = 'Password cracking',
    MOBILE_FORENSIC_TITLE = 'Forensic case',
    AUDIT_NETWORK_TITLE = 'Vulnerability scanning',
    TIW_TITLE = 'E-commerce',
    NAS_ENVIRONMENT_TITLE = 'My own cloud',
    GALAGA_TEXT = 'This game was developed using Java and some libraries offered by the University. Here I used some technical knowledge such as OOP, polymorphism or inheritance among others. This was my first programming project at the University.',
    OPENMP_TEXT = 'Using the OpenMP library, I developed an image processor to apply different filters on the images such as the Gaussian Blur or the Gaussian Operator, working with the pixel matrix.',
    DISTRIBUTED_SYS_TEXT = 'Written in C, I participated in the development of a messaging system using Sockets, RPC calls and Web Services in languages such as C and Java. In this project users could log into the system (being previously registered) and talk to each other using their username as a message prefix.',
    OPERATIVE_SYSTEM_DESIGN_TEXT = 'Using Raspberry Pi and environmental sensors, I built in Python an environmental temperature and humidity meter based on a specific geolocation communicated through REST API calls. All this information was processed in GCP (Google Cloud Platform) and deployed with Docker containers.',
    CRACKING_PASS_TEXT = 'Using controlled environments, I understood how Linux systems store credentials and how they can be breached by different types of attacks (dictionary, brute force, masks ...) using tools such as John The Ripper or Hashcat.',
    MOBILE_FORENSIC_TEXT = 'From an image of a mobile device the task was to find relevant user information that could create an identity of the person carrying it. Locations, passwords, money transactions, images and chats found were analyzed. Everything was performed in previously controlled environments using mainly Autopsy.',
    AUDIT_NETWORK_TEXT = 'Given images of potentially vulnerable machines with outdated operating systems, several vulnerability scans and exploits were performed on the CVEs found with Nessus software, Metasploit and the Linux terminal.',
    TIW_TEXT = 'Using the Spring boot Java framework, a Wallapop-style E-commerce application was developed based on microservices where users could register, buy products and sell them through the platform where banking transactions were simulated.',
    NAS_ENVIRONMENT_TEXT = 'In order to enjoy a cloud service at no extra cost and using a Raspberry Pi and a hard drive, I built a NAS system to store my information to which I have access from anywhere remotely having configured a VPN access.',
    MORE_TITLE = 'Next are incoming...',
    MORE_TEXT = 'Just be patient '
}